dist: focal

language: python
python:
    - "3.7"
install:
    - "pip install -r requirements.txt"

script:
    - export CI_TEST=0
    - "nosetests tbss/tests --nocapture --nologcapture --with-coverage --cover-inclusive --cover-erase --cover-package ."
after_success:
    - coveralls
